project:
  type: website
  output-dir: docs

website:
  title: "Ziling Zhen"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

