project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Ziling Zhen"
  site-url: https://zilingzhen.com
  navbar:
    background: dark
    left:
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
  page-footer: 
    background: dark
    left: © Ziling Zhen, 2026
    right: This website is built in [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

