project:
  type: website
  output-dir: docs

website:
  title: "Ziling Zhen"
  navbar:
    background: dark
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
  page-footer: 
    background: dark
    left: © Ziling Zhen, 2024
    right: This website is built in [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

