project:
  type: website
  output-dir: docs

website:
  title: "z1l1ng.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MiniProject1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

