<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-05-17">
<meta name="description" content="Final project for STAT 322 - Statistical Theory where I analyzed my own basketball shot chart in attempt to replicate Brian J. Reich, James S. Hodges, Bradley P. Carlin, and Adam M. Reich’s Bayesian statistic methods. Code referenced off of Oliver Chabot’s Ballbook for court &amp; zones, see here">

<title>Ziling Zhen - Shot Chart Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ziling Zhen</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methodsdata" id="toc-methodsdata" class="nav-link" data-scroll-target="#methodsdata">Methods/Data</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#replication-methodsdata" id="toc-replication-methodsdata" class="nav-link" data-scroll-target="#replication-methodsdata">Replication: Methods/Data</a></li>
  <li><a href="#results-discussion" id="toc-results-discussion" class="nav-link" data-scroll-target="#results-discussion">Results &amp; Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Shot Chart Analysis</h1>
</div>

<div>
  <div class="description">
    Final project for STAT 322 - Statistical Theory where I analyzed my own basketball shot chart in attempt to replicate Brian J. Reich, James S. Hodges, Bradley P. Carlin, and Adam M. Reich’s Bayesian statistic methods. Code referenced off of Oliver Chabot’s Ballbook for court &amp; zones, <a href="https://github.com/olivierchabot17/ballbook">see here</a>
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>To view the qmd of this project, click <a href="https://github.com/z1l1ng/z1l1ng.github.io/blob/main/projects/shotchart_folder/shotchart.qmd">here</a>.</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Basketball shot charts have gained much popularity over the years; a shot chart is a spatial representation of where a shot is taken, ‘o’s’ represent a success/make, and ‘x’s’ represent failure/missed shot. The best teams and players are now utilizing this chart to show shooting preferences, abilities, and tendencies of where a player likes to shoot. Brian J. Reich, James S. Hodges, Bradley P. Carlin, and Adam M. Reich knew that accurate inferences for shot charts would come from statistical models. These models have predictors that are time-varying and not. Shot frequency, shot location and shot selection were the three different response variables looked at, with a different type of model created for each one.</p>
</section>
<section id="methodsdata" class="level1">
<h1>Methods/Data</h1>
<p>Their approach consisted of using spatial models, and Markov chain Monte Carlo (MCMC) model methods to reflect on Sam Cassell’s shot chart for the 2003-2004 basketball season, Cassell took 1270 shots in the 82-game season, and 6 of the game’s data were not available and other issues were recorded but not in the shot chart thus they only modeled 1,139 of the shots. The shot chart data was used in 3 different ways, to predict shot frequency, shot location, and shot success, all of which accounted for various covariates, to turn a descriptive tool into an inferential one. A little introduction about the covariates:</p>
<ul>
<li><p>NOKG (Kevin Garnett is not in the game)</p></li>
<li><p>NOLS (Latrell Sprewell is not in the game)</p></li>
<li><p>HOME (played on home court)</p></li>
<li><p>NOREST (team had less than 2 days off since their last game)</p></li>
<li><p>BEHIND (losing the game), BLOCK (opponents average more than 4.8 blocks per game)</p></li>
<li><p>FGPALL (opponent allowed a field goal percentage under 44%)</p></li>
<li><p>MISSLAST (missed last shot)</p></li>
<li><p>TEAMFGA (team took more than 80 shots in the game).</p></li>
</ul>
<p>Shot Frequency: A multiple linear regression with the log of time between shots as the response, each of the covariates, two interaction terms, and a homogeneous error variance, thus assuming no heteroskedasticity. For the mean parameters normal priors were chosen with a mean of 0, and a variance of 1,000, for the error variance, the prior chosen was the inverse gamma function. An issue was that some of the covariates, such as NOKG, NOLS, and BEHIND, could change values between shot attempts, but the exact time of change is unknown, so an error-in-covariates was considered for the proportion of time between each shot.</p>
<p>Shot Location: Since the game is about making a basket, polar coordinates are used, in this case, it is the distance from the basket in feet. The court was divided into an eleven-by-eleven grid, however, the semi-circle within 2 feet they defined as Region 1, this region is in what we call the restricted area, this area is an arc extending 4 feet from in which its purpose is to prevent charges in this area thus the offensive player (the one shooting it) has more incentive to shoot it in this area if there is a defender there. Shots taken here are usually in transition or taken immediately following a rebound, so it was decided that this region would have no neighbors. Neighbors in spatial analysis are the regions that are adjacent to each other, since Cassell had cells at zero shot attempts and multiple cells had four or fewer attempts, neighboring cells played an important role in obtaining estimates of covariate effects. A statistical model now tests the significance of each covariate’s association with shot location. The conditionally autoregressive (CAR) distribution is often used as a prior in spatial modeling, this distribution is especially useful in this case since it is used to account for possible correlation among observations made across our regions. Where the spatially varying coefficient of covariate is given a CAR(<span class="math inline">\(\tau_k\)</span>) prior. Thus two types of neighbors were examined, angle neighbors, regions that are the same distance from the basket, and distance neighbors, adjacent regions that are the same angle from the middle of the court. Thus two neighbor relation CAR (2NRCAR) extends the CAR distribution to account for angle neighbors and distance neighbors. The prior for this is a bit more complex but simplifies to the usual CAR prior if <span class="math inline">\(\beta_k\)</span>=0.5; <span class="math inline">\(\beta_k\)</span>&gt;0.5 indicates stronger smoothing of angle neighbors, where <span class="math inline">\(\beta_k\)</span>&lt;0.5 indicates stronger smoothing of distance of neighbors, where <span class="math inline">\(\beta_k\)</span> is an indicator variable which determines the influence of the neighbor types. Each <span class="math inline">\(\beta_k\)</span> was given an independent Uniform(0,1) prior and <span class="math inline">\(\beta_k\)</span> was given independent Gamma(0.01, 0.01) priors <span class="citation" data-cites="reich_spatial_2006">(<a href="#ref-reich_spatial_2006" role="doc-biblioref">Reich et al. 2006</a>)</span>. The Markov chain Monte Carlo method comes into action here, this method allows “for parameter estimation such as means, variances, expected values, and exploration of the posterior distribution of Bayesian models”, this is done by simulation of random sampling <span class="citation" data-cites="noauthor_markov_2016">(<a href="#ref-noauthor_markov_2016" role="doc-biblioref"><span>“Markov <span>Chain</span> <span>Monte</span> <span>Carlo</span>”</span> 2016</a>)</span>. 30,000 samples from the posterior distribution were drawn, <span class="math inline">\(\beta_{kj}\)</span> was updated by normal distribution, and <span class="math inline">\(\beta_k\)</span> was updated by beta candidate distribution implementing a Metropolis-Hasting algorithm, thus meaning the Markov Chain converges to that distribution. At the same time, <span class="math inline">\(\tau_k\)</span> followed a gamma full conditional distribution, full condition distributions are distributions of each parameter given all the parameters in the data and was updated using Gibbs sampling. Then the models were compared using the deviance information criterion (DIC), a generalization of the AIC, thus penalizing larger models, thus a smaller DIC is desired.</p>
<p>Shot Success: Multiple logistic regressions were used to model the shooting percentage and the 2NRCAR prior was used to differentiate between smoothing of angle and distance neighbors.</p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>Shot Frequency: It was found that Cassell attempted an average of 15.0 shots per game and that the median game time between his shots was 1.6 minutes. The results of the error-in-covariates model were similar to a model that used only each covariate’s value at the time of the shot and was much simpler, thus the simpler model was used. It was found that the posterior median of the model with NOKG, NOLS, and NOKG*NOLS was 0.88, meaning that the posterior median time between shots was 12% shorter when both Sprewell and Garnett were not playing. The model with the interaction BEHIND and 2HALF/OT also had a 12% shorter posterior median time, the model with NOREST had a posterior median time that was 13% longer than if the team had more than 2 days off since their last game.</p>
<p>Shot Location: The final models showed the different effects of covariates and how they affected Cassell shot selection. It was found that removing Garnett or Sprewell does not significantly affect Cassell’s shot selection, there is also little significance of of MISSLAST in his shooting percentage. For BLOCK, 2HALF/OT, and NOREST the posterior median of <span class="math inline">\(\beta_k\)</span> was greater than 0.5, meaning greater smoothing of angle neighbors, thus these predictors have more influence of the distance than the angle.</p>
<p>Shot Success: It was found that they could not conclude that Cassell’s shooting percentage changes with distance more than with angle, but more so that his shooting percentage decreased when Garnett was not in the game</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Overall, this paper discussed a new way of using Bayesian statistics to analyze basketball shot charts. For shot frequency it was expected that Cassell take more of his shots in the fourth considering he was known for being a confident and end of game finisher. This however could be explained by the Timberwolves holding the ball near the end of the game, thus taking less shots, to keep the lead. In basketball there is a 24 countdown timer that starts when a team takes possession of the ball, it is strategic if you are winning to use as much of this time as possible to keep the other team from being able to score and catch up. However, in the models tested, BEHIND, and the interaction between BEHIND and 2HALF/OT was not significant goes against our original thought of Cassell shooting more in the 4th. For the models with NOKG, NOLS and NOKG*NOLS, the time between shots was shorter, this could be explained by Cassell having to step up and be more aggressive with those teammates out. However, for shot location it is found that Cassell will still shoot in the same spots with or without Garnett or Sprewell on the floor suggesting that he is consistent in his shots and his teammates don’t affect that even though typically depending on who you’re playing with their playing style affects yours. Some limitations for these models would be that Cassell was a star player, for the players who don’t play as much, don’t have as many shots to plot thus leaving more empty zone contributing to a weaker analysis.</p>
</section>
<section id="replication-methodsdata" class="level1">
<h1>Replication: Methods/Data</h1>
<p>I attempted to try to analyze my own basketball shot chart. This process involved lots of data manipulation and ultimately just running a multiple logistic regression model. First, I created my own dataset of all the shots I took (169) in the 2023-2024 season with the covariates:</p>
<ul>
<li><p>behind (1 for behind in the game, 0 not behind)</p></li>
<li><p>home, (1 for home court, 0 for not at home)</p></li>
<li><p>miss_last (1 for miss last shot, 0 for did not miss last shot)</p></li>
<li><p>no_rest (1 for less than 3 days since the last game, 0 for more than 3 days).</p></li>
</ul>
<p>Then, came the exploratory data analysis, I was able to plot all of these shots and aggregate my shots to fill in different zones of the shot chart <span class="citation" data-cites="chabot_1_nodate"><span>“Ballbook/01-Shots_data.<span>Rmd</span> at Main · Olivierchabot17/Ballbook”</span> (<a href="#ref-noauthor_ballbook01-shots_datarmd_nodate" role="doc-biblioref">n.d.</a>)</span>. Since I had taken significantly less shots than Cassell I opted for a five-by-four grid of twenty zones instead of an eleven-by-eleven. Finally, came the statistical modeling, again I attempted to figure out how to model my data by setting uninformative priors on my covariates but ultimately was unsuccessful thus I just did some regular spatial analysis and ran a logistic regression model. Keeping in mind I should’ve ran a mixed model instead to account for the non independence in my data, considering factors such as fatigue, confidence, and defensive pressure can affect shooting performance from one shot to the next, as well as shots taken from similar positions on the court may be influenced by similar factors such as distance from the basket, angle to the hoop, and defensive coverage.</p>
<p>This shot chart shows the location of my shots for the 2023-2024 Season. Green represents makes, where red represents misses. Out of the 169 shots taken (not including freethrows) I made 68 of those shots (40.24%), thus meaning I missed 101 of those shots (59.76%).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-5-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This shot chart shows the location of my shots for the 2023-2024 Season. Green represents makes, where red represents misses. Out of the 169 shots taken (not including freethrows) I made 68 of those shots (40.24%), thus meaning I missed 101 of those shots (59.76%).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-6-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">shot_zone_area</th>
<th style="text-align: right;">shots_taken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Left Side</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">Left Center</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Center</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Right Center</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Right Side</td>
<td style="text-align: right;">25</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">shot_zone_area</th>
<th style="text-align: left;">shot_made</th>
<th style="text-align: right;">shots_taken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Left Side</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Left Side</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Left Center</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Left Center</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Center</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Center</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Right Center</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Right Center</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Right Side</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Right Side</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, we’ve divided the court into 5 different angles, left side, left center, center, right center, and right side. We can see that I take the most shots from the left center and the right center. I shot 45.5% from the left side, 34.8% from left center, 53.3% from the center, 38% from the right center, and 40% from the right side.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-8-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">shot_zone_range</th>
<th style="text-align: right;">shots_taken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0-8 ft</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">8-16 ft</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16-24 ft</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">24+ ft</td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">shot_zone_range</th>
<th style="text-align: left;">shot_made</th>
<th style="text-align: right;">shots_taken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0-8 ft</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td style="text-align: left;">0-8 ft</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8-16 ft</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">8-16 ft</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16-24 ft</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">16-24 ft</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24+ ft</td>
<td style="text-align: left;">Miss</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">24+ ft</td>
<td style="text-align: left;">Make</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, we’ve divided the court into 4 different distances, 0-8 ft, 8-16 ft, 16-24 ft, and 24 ft. Taking my height into consideration 5 feet 5 inches it is not that unusual that the distance I take the most shots from is the 0-8 ft zone since most players my height are either really good at shooting the 3 point shot and/or really fast thus being able get past everyone with speed for a closer shot. I shot 44.4% from the 0-8 ft, 40% from 8-16 ft, 41.2% from 16-24 ft, and 25% from 24 ft.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-11-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now, we have our court divided up by distance and angles. Not going to go too much detail into percentages, but we can see that I do prefer certain zones on the court more than others.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">zones</th>
<th style="text-align: right;">shot_count</th>
<th style="text-align: right;">shots_missed</th>
<th style="text-align: right;">shots_made</th>
<th style="text-align: right;">shot_percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0-8 ft Center</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.8000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">0-8 ft Left Center</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.3600000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0-8 ft Left Side</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.5000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">0-8 ft Right Center</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.4000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0-8 ft Right Side</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.5555556</td>
</tr>
<tr class="even">
<td style="text-align: left;">16-24 ft Center</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.4285714</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16-24 ft Left Center</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">16-24 ft Left Side</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.5000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16-24 ft Right Center</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">16-24 ft Right Side</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3333333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24+ ft Center</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">24+ ft Left Center</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3333333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24+ ft Left Side</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1666667</td>
</tr>
<tr class="even">
<td style="text-align: left;">24+ ft Right Center</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2857143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24+ ft Right Side</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3333333</td>
</tr>
<tr class="even">
<td style="text-align: left;">8-16 ft Center</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8-16 ft Left Center</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.3529412</td>
</tr>
<tr class="even">
<td style="text-align: left;">8-16 ft Left Side</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.5333333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8-16 ft Right Center</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.3750000</td>
</tr>
<tr class="even">
<td style="text-align: left;">8-16 ft Right Side</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-13-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This shot chart shoes the number of shots total I took in each zone, with a white/lighter blues is a lower amount of shots taken and a darker blue means a higher amount.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-14-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This shot chart plots the percentages of makes by zone, in the table above we are able to see those specific percentages, for white/lighter blues is a lower percentages and a darker blue means a higher percentage.</p>
</section>
<section id="results-discussion" class="level1">
<h1>Results &amp; Discussion</h1>
<p><strong>Logistic Regression</strong></p>
<div class="cell">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:95%; ">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.2977110</td>
<td style="text-align: right;">1.0433097</td>
<td style="text-align: right;">1.2438405</td>
<td style="text-align: right;">0.2135583</td>
</tr>
<tr class="even">
<td style="text-align: left;">home</td>
<td style="text-align: right;">-0.6220014</td>
<td style="text-align: right;">0.9362024</td>
<td style="text-align: right;">-0.6643878</td>
<td style="text-align: right;">0.5064422</td>
</tr>
<tr class="odd">
<td style="text-align: left;">norest</td>
<td style="text-align: right;">1.8663761</td>
<td style="text-align: right;">1.1649889</td>
<td style="text-align: right;">1.6020548</td>
<td style="text-align: right;">0.1091435</td>
</tr>
<tr class="even">
<td style="text-align: left;">behind</td>
<td style="text-align: right;">1.3108624</td>
<td style="text-align: right;">0.9066775</td>
<td style="text-align: right;">1.4457868</td>
<td style="text-align: right;">0.1482370</td>
</tr>
<tr class="odd">
<td style="text-align: left;">miss_last</td>
<td style="text-align: right;">-8.2189173</td>
<td style="text-align: right;">1.4267968</td>
<td style="text-align: right;">-5.7603978</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<p>These are the exponentiated coefficients of the model.</p>
<div class="cell">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:95%; ">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.6609071</td>
</tr>
<tr class="even">
<td style="text-align: left;">home</td>
<td style="text-align: right;">0.5368689</td>
</tr>
<tr class="odd">
<td style="text-align: left;">norest</td>
<td style="text-align: right;">6.4648262</td>
</tr>
<tr class="even">
<td style="text-align: left;">behind</td>
<td style="text-align: right;">3.7093712</td>
</tr>
<tr class="odd">
<td style="text-align: left;">miss_last</td>
<td style="text-align: right;">0.0002695</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<p>I ran a model with all of my predictors I had in my dataset to see if any them were significant, the only one that was, was miss_last, this was weird however because its standard error was the largest out of all of the predictors. The predicted odds that I make my shot decrease by 99.97% if I missed the shot before that, and you keep the predictors home, behind and no rest constant. This feels very accurate in that I know my confidence decreases when I miss a shot therefore contributing bad feelings that could potentially cause me to miss the next one, but shooters got to shoot. The predicted odds that I make my shot are 3.66, if it is not a home game, if we got more than 3 days of rest, if we were behind in the game and if I missed the shot previous to this attempt.</p>
<div class="cell">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:95%; ">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.386294</td>
<td style="text-align: right;">1.118034</td>
<td style="text-align: right;">1.2399394</td>
<td style="text-align: right;">0.2149978</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones0-8 ft Left Center</td>
<td style="text-align: right;">-1.961658</td>
<td style="text-align: right;">1.193152</td>
<td style="text-align: right;">-1.6440981</td>
<td style="text-align: right;">0.1001559</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones0-8 ft Left Side</td>
<td style="text-align: right;">-1.386294</td>
<td style="text-align: right;">1.322876</td>
<td style="text-align: right;">-1.0479400</td>
<td style="text-align: right;">0.2946662</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones0-8 ft Right Center</td>
<td style="text-align: right;">-1.791759</td>
<td style="text-align: right;">1.190238</td>
<td style="text-align: right;">-1.5053791</td>
<td style="text-align: right;">0.1322266</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones0-8 ft Right Side</td>
<td style="text-align: right;">-1.163151</td>
<td style="text-align: right;">1.303840</td>
<td style="text-align: right;">-0.8920959</td>
<td style="text-align: right;">0.3723415</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Center</td>
<td style="text-align: right;">-1.673976</td>
<td style="text-align: right;">1.354006</td>
<td style="text-align: right;">-1.2363135</td>
<td style="text-align: right;">0.2163420</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones16-24 ft Left Center</td>
<td style="text-align: right;">-16.952363</td>
<td style="text-align: right;">1455.397962</td>
<td style="text-align: right;">-0.0116479</td>
<td style="text-align: right;">0.9907065</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Left Side</td>
<td style="text-align: right;">-1.386294</td>
<td style="text-align: right;">1.500000</td>
<td style="text-align: right;">-0.9241962</td>
<td style="text-align: right;">0.3553842</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones16-24 ft Right Center</td>
<td style="text-align: right;">-1.386294</td>
<td style="text-align: right;">1.802776</td>
<td style="text-align: right;">-0.7689778</td>
<td style="text-align: right;">0.4419065</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Right Side</td>
<td style="text-align: right;">-2.079442</td>
<td style="text-align: right;">1.658312</td>
<td style="text-align: right;">-1.2539504</td>
<td style="text-align: right;">0.2098600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Center</td>
<td style="text-align: right;">-16.952363</td>
<td style="text-align: right;">1455.397962</td>
<td style="text-align: right;">-0.0116479</td>
<td style="text-align: right;">0.9907065</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones24+ ft Left Center</td>
<td style="text-align: right;">-2.079442</td>
<td style="text-align: right;">1.658312</td>
<td style="text-align: right;">-1.2539504</td>
<td style="text-align: right;">0.2098600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Left Side</td>
<td style="text-align: right;">-2.995732</td>
<td style="text-align: right;">1.565248</td>
<td style="text-align: right;">-1.9139031</td>
<td style="text-align: right;">0.0556325</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones24+ ft Right Center</td>
<td style="text-align: right;">-2.302585</td>
<td style="text-align: right;">1.396424</td>
<td style="text-align: right;">-1.6489154</td>
<td style="text-align: right;">0.0991650</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Right Side</td>
<td style="text-align: right;">-2.079442</td>
<td style="text-align: right;">1.658312</td>
<td style="text-align: right;">-1.2539504</td>
<td style="text-align: right;">0.2098600</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Center</td>
<td style="text-align: right;">-1.386294</td>
<td style="text-align: right;">1.802776</td>
<td style="text-align: right;">-0.7689778</td>
<td style="text-align: right;">0.4419065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones8-16 ft Left Center</td>
<td style="text-align: right;">-1.992430</td>
<td style="text-align: right;">1.227834</td>
<td style="text-align: right;">-1.6227198</td>
<td style="text-align: right;">0.1046493</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Left Side</td>
<td style="text-align: right;">-1.252763</td>
<td style="text-align: right;">1.232014</td>
<td style="text-align: right;">-1.0168420</td>
<td style="text-align: right;">0.3092286</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones8-16 ft Right Center</td>
<td style="text-align: right;">-1.897120</td>
<td style="text-align: right;">1.231530</td>
<td style="text-align: right;">-1.5404575</td>
<td style="text-align: right;">0.1234489</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Right Side</td>
<td style="text-align: right;">-2.233592</td>
<td style="text-align: right;">1.313846</td>
<td style="text-align: right;">-1.7000415</td>
<td style="text-align: right;">0.0891231</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<p>These are the exponentiated coefficients of the model.</p>
<div class="cell">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:95%; ">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones0-8 ft Left Center</td>
<td style="text-align: right;">0.1406250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones0-8 ft Left Side</td>
<td style="text-align: right;">0.2500000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones0-8 ft Right Center</td>
<td style="text-align: right;">0.1666667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones0-8 ft Right Side</td>
<td style="text-align: right;">0.3125000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Center</td>
<td style="text-align: right;">0.1875000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones16-24 ft Left Center</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Left Side</td>
<td style="text-align: right;">0.2500000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones16-24 ft Right Center</td>
<td style="text-align: right;">0.2500000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones16-24 ft Right Side</td>
<td style="text-align: right;">0.1250000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Center</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones24+ ft Left Center</td>
<td style="text-align: right;">0.1250000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Left Side</td>
<td style="text-align: right;">0.0500000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones24+ ft Right Center</td>
<td style="text-align: right;">0.1000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones24+ ft Right Side</td>
<td style="text-align: right;">0.1250000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Center</td>
<td style="text-align: right;">0.2500000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones8-16 ft Left Center</td>
<td style="text-align: right;">0.1363636</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Left Side</td>
<td style="text-align: right;">0.2857143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zones8-16 ft Right Center</td>
<td style="text-align: right;">0.1500000</td>
</tr>
<tr class="even">
<td style="text-align: left;">zones8-16 ft Right Side</td>
<td style="text-align: right;">0.1071429</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<p>This model looks at zones that are part of the eleven-by-eleven grid. None of these zones are significant at the 0.05 level. We can see that if I shoot it from 0-8 ft range in the center the predicted odds I make the shot are 4.00, shooting it from anywhere else the predicted odds decrease from 99.99% to 69%.</p>
<p>I also ran a model with zones and miss_last, and their interaction, none of the coefficients were significant. Out of curiosity I ran a drop-in-deviance test to see if the addition of the interaction term was significant. To my surprise it was. However, with the amount of zones some didn’t have a make and a miss in the zone thus that interaction did not exist.</p>
<p>This project has sparked some curiosity what more I can do with this dataset. I hope that one day I’ll understand more complex models in the spatial world to replicate setting priors on my covariates for posterior parameters.</p>
<p><strong>Spatial Analysis For Fun (Quadrat Test &amp; Moran’s I)</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-20-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Testing for clustering! Looking at our shot chart by eye, there is apparent clustering, primarily on the left (angle) and right (angle) areas.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/unnamed-chunk-22-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is the window of shots we are going to keep in our analysis, this removes two shots that typically aren’t going to take.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shotchart_files/figure-html/quadrat-count-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>If the shots were spatially random, then we can imagine that the observed number of points within each cell would be similar for all equally sized cells. This is definitely NOT the case. To confirm it we run a quadrat test, the Chi-squared test of CSR, to test for distribution patterns such as clustering and randomness.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  shots_ppp
X2 = 366.56, df = 24, p-value &lt; 2.2e-16
alternative hypothesis: two.sided

Quadrats: 25 tiles (irregular windows)</code></pre>
</div>
</div>
<p>We can see that based off the quadrat test there’s a <span class="math inline">\(\chi^2\)</span> value of 366.56 and p-value of <span class="math inline">\(2.2 \times 10^{-16}\)</span>, which is SUPER small, thus we can reject the null hypothesis and conclude that this does not follow the Chi-squared distribution and that there is clustering of the shots I took in the season.</p>
<p><strong>Moran’s I</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  shots_aggregated$shot_count 
weights: shots_nbw  
number of simulations + 1: 500 

statistic = 0.17458, observed rank = 470, p-value = 0.06
alternative hypothesis: greater</code></pre>
</div>
</div>
<p><strong>Our Test</strong></p>
<p><span class="math inline">\(H_O\)</span>: No spatial autocorrelation, I is close to 0</p>
<p><span class="math inline">\(H_A\)</span>: Spatial autocorrelation, I <span class="math inline">\(\neq\)</span> 0.</p>
<p>Calculating Moran’s I for the number of shots taken in using Monte Carlo’s simulations we get a Moran’s I of 0.175 which is positive and weak. We got a p-value of 0.078. We can not reject the null hypothesis and conclude that there is not significant evidence that the number of shots taken is spatially autocorrelated. It is pretty apparent in my shot chart that I prefer to shoot more in some areas than others.</p>
<p>The record of the team this year was 4-20 so for the predictor “behind” we were pretty much behind in every game meaning that I was playing pretty much the same whether we were winning or losing. For home or away, the best two games I played this year were both away game, meaning I was pretty consistent playing well at home and away since most player do play significantly better in a place they’re familiar with. In the future I would like to add my shots from the 23-24 and 24-25 season to see my overall percentages and see if my shots are still super clustered, hopefully with more data I will be able to run a mixed model since I’ll hopefully have enough shots in every zone.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-noauthor_ballbook01-shots_datarmd_nodate" class="csl-entry" role="listitem">
<span>“Ballbook/01-Shots_data.<span>Rmd</span> at Main · Olivierchabot17/Ballbook.”</span> n.d. <em>GitHub</em>. Accessed May 16, 2024. <a href="https://github.com/olivierchabot17/ballbook/blob/main/01-shots_data.Rmd">https://github.com/olivierchabot17/ballbook/blob/main/01-shots_data.Rmd</a>.
</div>
<div id="ref-chabot_1_nodate" class="csl-entry" role="listitem">
Chabot, Olivier. n.d. <em>1 <span>Overview</span> <span></span> <span>Spatial</span> <span>Analysis</span> of <span>Basketball</span> <span>Shots</span> in <span>R</span></em>. Accessed May 16, 2024. <a href="https://duddhawork.com/ballbook/index.html">https://duddhawork.com/ballbook/index.html</a>.
</div>
<div id="ref-noauthor_markov_2016" class="csl-entry" role="listitem">
<span>“Markov <span>Chain</span> <span>Monte</span> <span>Carlo</span>.”</span> 2016. <em>Columbia University Mailman School of Public Health</em>. <a href="https://www.publichealth.columbia.edu/research/population-health-methods/markov-chain-monte-carlo">https://www.publichealth.columbia.edu/research/population-health-methods/markov-chain-monte-carlo</a>.
</div>
<div id="ref-reich_spatial_2006" class="csl-entry" role="listitem">
Reich, Brian J., James S. Hodges, Bradley P. Carlin, and Adam M. Reich. 2006. <span>“A <span>Spatial</span> <span>Analysis</span> of <span>Basketball</span> <span>Shot</span> <span>Chart</span> <span>Data</span>.”</span> <em>The American Statistician</em> 60 (1): 3–12. <a href="https://www.jstor.org/stable/27643720">https://www.jstor.org/stable/27643720</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Ziling Zhen, 2024</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built in <a href="https://quarto.org/" target="_blank">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>